### ISSUE TITLE
about LeCaRDv2 judgment labels

### ISSUE THREAD

**Issue by zotown** [E-qin/GEAR#1]
It is mentioned in the paper that since LeCaRDv2 queries have no labels and you invited legal experts to label them. Would you mind sharing the data of the ground-truth judgment labels? Thanks!

**Comment by E-qin** [comment]
Sorry for the delay in uploading the data. It's up now. Let me know if you need anything else :)

**Comment by E-qin** [comment]
'GEAR/dataset/LeCaRD_version2/LeCaRD_version2_key_src/test_q_charges.json'. It aligns with the order of ’GEAR/dataset/LeCaRD_version2/LeCaRD_version2_key_src/test_q_charges.json‘.

**Comment by E-qin** [comment]
`GEAR/dataset/LeCaRD_version2/LeCaRD_version2_key_src/test_q_charges.json`. It aligns with the order of `GEAR/dataset/LeCaRD_version2/LeCaRD_version2_key_src/test_qids.json`.

**Comment by zotown** [comment]
> `GEAR/dataset/LeCaRD_version2/LeCaRD_version2_key_src/test_q_charges.json`. It aligns with the order of `GEAR/dataset/LeCaRD_version2/LeCaRD_version2_key_src/test_qids.json`.

thanks!
